#!/usr/bin/env bash
# ==============================================================================
# Solar Panel AI Inspection System — EC2 Deploy Script
#
# Builds and starts both containers on EC2 with the correct EC2 public IP
# embedded into the Next.js frontend build.
#
# Usage (on EC2 or from a CI/CD system):
#   chmod +x scripts/deploy.sh
#   bash scripts/deploy.sh <EC2_PUBLIC_IP>
#
# Example:
#   bash scripts/deploy.sh 54.123.45.67
#
# If no IP is given, it is read from the EC2_PUBLIC_IP env variable.
# If that is also unset, the script exits with an error.
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------
# Resolve EC2 public IP
# ------------------------------------------------------------------
EC2_PUBLIC_IP="${1:-${EC2_PUBLIC_IP:-}}"

if [[ -z "$EC2_PUBLIC_IP" ]]; then
    echo "ERROR: EC2 public IP not specified."
    echo "Usage: bash scripts/deploy.sh <EC2_PUBLIC_IP>"
    echo "   or: EC2_PUBLIC_IP=1.2.3.4 bash scripts/deploy.sh"
    exit 1
fi

BACKEND_URL="http://${EC2_PUBLIC_IP}:8000"

echo "====================================================="
echo " Solar Panel AI EC2 Deploy — $(date -u)"
echo " EC2 Public IP : ${EC2_PUBLIC_IP}"
echo " Backend URL   : ${BACKEND_URL}"
echo "====================================================="

# ------------------------------------------------------------------
# Write .env for this deployment
# ------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"

echo "[1/5] Writing .env file..."
cat > "${APP_DIR}/.env" <<EOF
# Auto-generated by deploy.sh — $(date -u)
# Do NOT commit this file.

# Database
DATABASE_URL=sqlite:////app/data/solar_panel_ai.db

# Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000

# Frontend — must point to the EC2-accessible backend address
# Browser requests originate from the user's machine, NOT from inside Docker.
NEXT_PUBLIC_API_BASE_URL=${BACKEND_URL}
NEXT_PUBLIC_API_URL=${BACKEND_URL}
EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
EOF

echo "    .env written with NEXT_PUBLIC_API_BASE_URL=${BACKEND_URL}"

# ------------------------------------------------------------------
# Pull latest source (optional — only if managing via git on EC2)
# ------------------------------------------------------------------
# Uncomment to enable automatic git pull before deploy:
# echo "[1b] Pulling latest source..."
# git -C "${APP_DIR}" pull --ff-only

# ------------------------------------------------------------------
# Build images (with correct NEXT_PUBLIC_API_BASE_URL baked in)
# ------------------------------------------------------------------
echo "[2/5] Building Docker images..."
cd "${APP_DIR}"
docker compose build \
    --build-arg NEXT_PUBLIC_API_BASE_URL="${BACKEND_URL}" \
    --build-arg NEXT_PUBLIC_API_URL="${BACKEND_URL}"

# ------------------------------------------------------------------
# Ensure data directory exists on host for SQLite persistence
# ------------------------------------------------------------------
echo "[3/5] Ensuring data directory exists..."
mkdir -p "${APP_DIR}/data"

# ------------------------------------------------------------------
# Start containers in detached mode
# ------------------------------------------------------------------
echo "[4/5] Starting containers..."
docker compose up -d

# ------------------------------------------------------------------
# Verify health
# ------------------------------------------------------------------
echo "[5/5] Waiting for backend health check..."
sleep 5

MAX_RETRIES=12
RETRY=0
until curl -sf "http://localhost:8000/api/health" > /dev/null 2>&1; do
    RETRY=$((RETRY + 1))
    if [[ $RETRY -ge $MAX_RETRIES ]]; then
        echo "ERROR: Backend did not become healthy after $((MAX_RETRIES * 5))s."
        docker compose logs backend
        exit 1
    fi
    echo "  Waiting for backend... (attempt ${RETRY}/${MAX_RETRIES})"
    sleep 5
done

echo ""
echo "====================================================="
echo " Deployment complete — $(date -u)"
echo ""
echo " SERVICES:"
docker compose ps
echo ""
echo " BACKEND  : http://${EC2_PUBLIC_IP}:8000"
echo " FRONTEND : http://${EC2_PUBLIC_IP}:3000"
echo " API DOCS : http://${EC2_PUBLIC_IP}:8000/docs"
echo " HEALTH   : $(curl -s http://localhost:8000/api/health)"
echo "====================================================="
