import {
  InspectionResponse,
  PanelResponse,
} from "@/types/inspection";

export const MOCK_PANELS: PanelResponse[] = [
  {
    id: 1,
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    created_at: "2022-01-15T08:00:00Z",
    installation_date: "Jan 15, 2022",
    rated_power_wp: 450,
    inverter_string: "String INV-04-A",
    azimuth_tilt: "28° South-Facing (180° S)",
    technology: "Monocrystalline N-Type",
    rack_coordinates: "Rack 04 · Row 12 · Pos 03",
    health_index: 71,
    total_scans: 14,
    latest_fault: "Electrical-damage",
    latest_severity: "HIGH",
    latest_urgency: "IMMEDIATE REVIEW",
    last_inspected: "Oct 24, 2023, 14:22 UTC",
    is_demo_sample: true,
  },
  {
    id: 2,
    panel_id: "SP-HYD-002",
    location: "Block B - Rooftop 2",
    created_at: "2022-02-10T09:30:00Z",
    installation_date: "Feb 10, 2022",
    rated_power_wp: 450,
    inverter_string: "String INV-02-B",
    azimuth_tilt: "28° South-Facing (180° S)",
    technology: "Monocrystalline N-Type",
    rack_coordinates: "Rack 02 · Row 05 · Pos 08",
    health_index: 78,
    total_scans: 11,
    latest_fault: "Physical-damage",
    latest_severity: "HIGH",
    latest_urgency: "PRIORITY",
    last_inspected: "Today, 11:05",
    is_demo_sample: true,
  },
  {
    id: 3,
    panel_id: "SP-HYD-003",
    location: "Engineering Building - Roof",
    created_at: "2022-03-01T11:00:00Z",
    installation_date: "Mar 01, 2022",
    rated_power_wp: 400,
    inverter_string: "String INV-01-A",
    azimuth_tilt: "25° South-Facing (180° S)",
    technology: "Polycrystalline Standard",
    rack_coordinates: "Rack 01 · Row 02 · Pos 04",
    health_index: 88,
    total_scans: 9,
    latest_fault: "Bird-drop",
    latest_severity: "MEDIUM",
    latest_urgency: "SCHEDULED",
    last_inspected: "Yesterday, 16:40",
    is_demo_sample: true,
  },
  {
    id: 4,
    panel_id: "SP-HYD-004",
    location: "Block A - Rooftop 1",
    created_at: "2022-01-15T08:00:00Z",
    installation_date: "Jan 15, 2022",
    rated_power_wp: 450,
    inverter_string: "String INV-04-B",
    azimuth_tilt: "28° South-Facing (180° S)",
    technology: "Monocrystalline N-Type",
    rack_coordinates: "Rack 04 · Row 12 · Pos 04",
    health_index: 92,
    total_scans: 8,
    latest_fault: "Dusty",
    latest_severity: "LOW",
    latest_urgency: "ROUTINE",
    last_inspected: "Yesterday, 09:15",
    is_demo_sample: true,
  },
  {
    id: 5,
    panel_id: "SP-HYD-005",
    location: "Block B - Rooftop 2",
    created_at: "2022-02-10T09:30:00Z",
    installation_date: "Feb 10, 2022",
    rated_power_wp: 450,
    inverter_string: "String INV-02-A",
    azimuth_tilt: "28° South-Facing (180° S)",
    technology: "Monocrystalline N-Type",
    rack_coordinates: "Rack 02 · Row 05 · Pos 09",
    health_index: 99,
    total_scans: 15,
    latest_fault: "Clean",
    latest_severity: "LOW",
    latest_urgency: "ROUTINE",
    last_inspected: "Oct 24, 2023",
    is_demo_sample: true,
  },
  {
    id: 6,
    panel_id: "SP-HYD-006",
    location: "Engineering Building - Roof",
    created_at: "2022-03-01T11:00:00Z",
    installation_date: "Mar 01, 2022",
    rated_power_wp: 400,
    inverter_string: "String INV-01-B",
    azimuth_tilt: "25° South-Facing (180° S)",
    technology: "Polycrystalline Standard",
    rack_coordinates: "Rack 01 · Row 03 · Pos 01",
    health_index: 85,
    total_scans: 7,
    latest_fault: "Snow-Covered",
    latest_severity: "MEDIUM",
    latest_urgency: "SCHEDULED",
    last_inspected: "Oct 23, 2023",
    is_demo_sample: true,
  },
  {
    id: 7,
    panel_id: "SP-HYD-007",
    location: "Block A - Rooftop 1",
    created_at: "2022-01-15T08:00:00Z",
    installation_date: "Jan 15, 2022",
    rated_power_wp: 450,
    inverter_string: "String INV-04-A",
    azimuth_tilt: "28° South-Facing (180° S)",
    technology: "Monocrystalline N-Type",
    rack_coordinates: "Rack 04 · Row 12 · Pos 05",
    health_index: 68,
    total_scans: 12,
    latest_fault: "Electrical-damage",
    latest_severity: "HIGH",
    latest_urgency: "IMMEDIATE REVIEW",
    last_inspected: "Oct 22, 2023",
    is_demo_sample: true,
  },
];

export const MOCK_INSPECTIONS: InspectionResponse[] = [
  {
    inspection_id: "INS-2023-8841",
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    image_filename: "panel_rgb_inspection_042.jpg",
    inspection_timestamp: "2023-10-24T14:22:18Z",
    predicted_class: "Electrical-damage",
    sub_fault: "Localized Discoloration / Burn Anomaly",
    confidence: 0.968,
    visual_region_area_percent: 14.8,
    severity: "HIGH",
    urgency: "IMMEDIATE REVIEW",
    maintenance_action:
      "Immediate Dispatch: Dispatch certified technician to Block A - Rooftop 1 within 24 hours. Perform physical electrical test on String #04 to isolate potential bypass diode or interconnect fault. Verify cell condition before restarting string.",
    manual_inspection_recommended: true,
    confidence_warning: null,
    bbox: [142, 88, 290, 185],
    original_image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuClu9_LnwC1NQr9D9IL_YRk0G3iChTCUSzuRi3UCDO9Dfv9QtZq7gHbu38Hoj6g3gEY09fG0Ar6xS_--_c4k0lyAzGNlr-OZ7xtDPysKf1efYN1wCU_eRp7LPqcGGHmcVF1KlOj3utNLMbe_3pj1twTjdKsle077yF2JW57TmLovR6Ekw_pZxm5xjWY3geAATZ9R3srg_HXr9DJ2FDYxqU-I8b0YLbyUaeEHemeOf3hLeXt3WEJLAq-KA",
    gradcam_image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBTQZK5eOuP_wR4SuHW_doQ7vTB7nX4yRLqcoeDY1ckYJVcPC-lFhkePC60bbRNCMfAkRcLwwwTzjfJD2h8rPjd4snm5WjRPGi9jsPZXBE0sWKqNKcwzFrZsHym--C1KRO1s8kHDO67NNDVv2yi_lUXzv6gqsiZvWlvKRxOI37GpzrIxs2o13zX2-NAMbEueokGBIb9jM6IGttmHBdUzBBws3lFlSdFjWJ2DXLI2WW25MyctUCm24zrzQ",
    region_image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDbFDONeqnQUktFSLCv03a2aeumzUqoFQvnB2DboBJE3RGKn9-dMxa8QYC00CUGe_YQQZ1Ra_ddGhi9InhApMWUtTkjnNSsS64QubI3WEOgcIsMi_uIKeddqJtRqvJyBat-dCKErDHciQpiLsQWBwZ2eBjF8e69v7PYDgeOphhHf3QF1BIhDDPLa4hVoLA7P4NHBqYcE3aQhWz921AOm2dWaKDWLzcdb8k92JeUPrAOfqhbTwtkQQfBWA",
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8839",
    panel_id: "SP-HYD-002",
    location: "Block B - Rooftop 2",
    image_filename: "panel_rgb_crack_b2_09.jpg",
    inspection_timestamp: "2023-10-24T11:05:00Z",
    predicted_class: "Physical-damage",
    sub_fault: "Surface Glass Crack Fracture",
    confidence: 0.912,
    visual_region_area_percent: 8.4,
    severity: "HIGH",
    urgency: "PRIORITY",
    maintenance_action:
      "Schedule physical structural inspection of module glass. Evaluate crack propagation using manual inspection and confirm whether panel replacement is required.",
    manual_inspection_recommended: true,
    confidence_warning: null,
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8822",
    panel_id: "SP-HYD-003",
    location: "Engineering Building - Roof",
    image_filename: "panel_rgb_bird_014.jpg",
    inspection_timestamp: "2023-10-23T16:40:00Z",
    predicted_class: "Bird-drop",
    sub_fault: "Surface Organic Soiling",
    confidence: 0.885,
    visual_region_area_percent: 5.2,
    severity: "MEDIUM",
    urgency: "SCHEDULED",
    maintenance_action:
      "Schedule surface washing during regular maintenance window to prevent localized cell shading and hotspot development.",
    manual_inspection_recommended: false,
    confidence_warning: null,
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8805",
    panel_id: "SP-HYD-004",
    location: "Block A - Rooftop 1",
    image_filename: "panel_rgb_dusty_sec4.jpg",
    inspection_timestamp: "2023-10-23T09:15:00Z",
    predicted_class: "Dusty",
    sub_fault: "Diffuse Airborne Soiling Layer",
    confidence: 0.94,
    visual_region_area_percent: 42.1,
    severity: "LOW",
    urgency: "ROUTINE",
    maintenance_action:
      "Routine surface wash recommended during standard washing cycle. Visual dust accumulation is widespread across active cell area.",
    manual_inspection_recommended: false,
    confidence_warning: null,
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8789",
    panel_id: "SP-HYD-005",
    location: "Block B - Rooftop 2",
    image_filename: "panel_rgb_clean_norm.jpg",
    inspection_timestamp: "2023-10-24T08:00:00Z",
    predicted_class: "Clean",
    sub_fault: "Clean / Nominal Condition",
    confidence: 0.991,
    visual_region_area_percent: 0.0,
    severity: "LOW",
    urgency: "ROUTINE",
    maintenance_action:
      "Nominal visual condition. No cleaning or repair required. Re-evaluate on standard quarterly inspection schedule.",
    manual_inspection_recommended: false,
    confidence_warning: null,
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8750",
    panel_id: "SP-HYD-006",
    location: "Engineering Building - Roof",
    image_filename: "panel_rgb_snow_east.jpg",
    inspection_timestamp: "2023-10-23T14:10:00Z",
    predicted_class: "Snow-Covered",
    sub_fault: "Partial / Full Snow Occlusion",
    confidence: 0.924,
    visual_region_area_percent: 68.5,
    severity: "MEDIUM",
    urgency: "SCHEDULED",
    maintenance_action:
      "Surface snow accumulation detected visually. Allow natural solar shedding or monitor for sustained freeze blockage.",
    manual_inspection_recommended: false,
    confidence_warning: null,
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-2023-8722",
    panel_id: "SP-HYD-007",
    location: "Block A - Rooftop 1",
    image_filename: "panel_rgb_hotspot_sec4.jpg",
    inspection_timestamp: "2023-10-22T15:30:00Z",
    predicted_class: "Electrical-damage",
    sub_fault: "Visible Localized Burn Mark",
    confidence: 0.68,
    visual_region_area_percent: 18.2,
    severity: "HIGH",
    urgency: "IMMEDIATE REVIEW",
    maintenance_action:
      "Severe visible electrical burn mark detected. Low model confidence (< 0.70); manual physical inspection strongly recommended to prevent damage propagation.",
    manual_inspection_recommended: true,
    confidence_warning:
      "Low model confidence (0.6800 < 0.70); manual physical inspection strongly recommended.",
    is_demo_sample: true,
  },
];

// Historical inspections specifically for SP-HYD-001 (shown in Panel Details)
export const MOCK_PANEL_001_INSPECTIONS: (InspectionResponse & {
  sensor_source: string;
})[] = [
  {
    ...MOCK_INSPECTIONS[0],
    inspection_id: "INS-8841",
    sensor_source: "High-Res Optical Camera",
  },
  {
    inspection_id: "INS-8798",
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    image_filename: "sp_hyd_001_rgb_oct20.jpg",
    inspection_timestamp: "2023-10-20T13:45:00Z",
    predicted_class: "Electrical-damage",
    sub_fault: "Visible Cell Discoloration",
    confidence: 0.974,
    visual_region_area_percent: 16.5,
    severity: "HIGH",
    urgency: "IMMEDIATE REVIEW",
    maintenance_action:
      "Verify cell condition with multimeter electrical test.",
    manual_inspection_recommended: true,
    sensor_source: "Handheld Optical Camera",
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-8620",
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    image_filename: "sp_hyd_001_rgb_sep14.jpg",
    inspection_timestamp: "2023-09-14T10:15:00Z",
    predicted_class: "Dusty",
    sub_fault: "Moderate Dust Accumulation",
    confidence: 0.91,
    visual_region_area_percent: 38.0,
    severity: "LOW",
    urgency: "ROUTINE",
    maintenance_action: "Standard surface cleaning completed.",
    manual_inspection_recommended: false,
    sensor_source: "Aerial RGB Survey",
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-8451",
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    image_filename: "sp_hyd_001_rgb_aug02.jpg",
    inspection_timestamp: "2023-08-02T16:30:00Z",
    predicted_class: "Clean",
    sub_fault: "Nominal Condition",
    confidence: 0.994,
    visual_region_area_percent: 0.0,
    severity: "LOW",
    urgency: "ROUTINE",
    maintenance_action: "Module surface in nominal condition.",
    manual_inspection_recommended: false,
    sensor_source: "Handheld Optical Camera",
    is_demo_sample: true,
  },
  {
    inspection_id: "INS-8104",
    panel_id: "SP-HYD-001",
    location: "Block A - Rooftop 1",
    image_filename: "sp_hyd_001_rgb_may18.jpg",
    inspection_timestamp: "2023-05-18T11:00:00Z",
    predicted_class: "Bird-drop",
    sub_fault: "Localized Dropping",
    confidence: 0.892,
    visual_region_area_percent: 4.8,
    severity: "MEDIUM",
    urgency: "SCHEDULED",
    maintenance_action: "Scheduled spot cleaning.",
    manual_inspection_recommended: false,
    sensor_source: "Aerial RGB Survey",
    is_demo_sample: true,
  },
];
